### ISSUE TITLE
JamWeapon - local 'WeaponSlot' is nil

### ISSUE THREAD

**Issue by Pardison** [DonHulieo/qb-weapons#1]
local WeaponSlot = PlayerData.items[CurrentWeaponData.slot] is a  nil value
   
   SCRIPT ERROR: @qb-weapons/client/mina/lua:160: attempt to index a nil value (local 'WeaponSlot')

**Comment by DonHulieo** [comment]
Yea weapons jamming is currently broken, will update to remove. Need to find a way to make sure people can't just switch weapons to get rid of the jammed weapon. My apologies

**Comment by DonHulieo** [comment]
Code for this is commented out, everything else should still be functional.

**Comment by DonHulieo** [comment]
After extensive testing of gun jamming, I've found if contained within qb-weapons it's very server intensive. This is probably due to bad coding on my part, so I'll be working on this but it won't be apart of this script.
