### ISSUE TITLE
when you run out of ammunition it gives this error even though you have ammunition in your inventory

### ISSUE THREAD

**Issue by eidertuning** [DonHulieo/qb-weapons#2]
SCRIPT ERROR: @qb-weapons/server/main.lua:231: attempt to perform arithmetic on a nil value (field 'quality')

**Comment by DonHulieo** [comment]
Hey I'll do some testing on this and see if I can replicate.

**Comment by DonHulieo** [comment]
Couldn't replicate this mate, and if I'm honest it sounds kind of strange. I've coded something that should stop this from happening although  and updated the script, going to close this issue.
