### ISSUE TITLE
Attempt to perform arithmetic on a nil value (local 'DecreaseAttach') 

### ISSUE THREAD

**Issue by bigramb0** [DonHulieo/qb-weapons#3]
<img width="1227" alt="Screen Shot 2022-11-20 at 12 03 28 AM" src="https://user-images.githubusercontent.com/84361647/202886560-64093f8a-2676-471a-9ea2-a3e102d8bcf5.png">

Still getting this error on latest version when shooting weapons with attachments.

**Comment by DonHulieo** [comment]
Are you using an inventory system with decay? Because if not, attachment won't already have quality defined.

**Comment by bigramb0** [comment]
No, just using qb-inventory. I might add a config to opt out of attachment durability and pr if you're cool w it?

**Comment by DonHulieo** [comment]
Of course! I'm actually bring an optimization update out for this when I finish something else I'm working on. I'll leave this issue open until your PR :).
