### ISSUE TITLE
F8 DecreaseAttach Error

### ISSUE THREAD

**Issue by KSJHub** [DonHulieo/qb-weapons#5]
![pjkapj](https://user-images.githubusercontent.com/83096833/205183411-d06ea754-d032-4d59-8488-557d4f3d4cad.png)

Hey don, after a fresh install. (just changing weapon damage modifier in config) we get this error when shooting. Assume its attachments. this was used with combat pistol no attachments. / standard pistol ammo

**Comment by DonHulieo** [comment]
Thanks mate, was anything removed from the config at all, or we’re numbers just changed? As a fix for now, if you make Config.AttachmentDurabilty false.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: KSJ ***@***.***>
Sent: Friday, December 2, 2022 10:54:27 AM
To: DonHulieo/qb-weapons ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DonHulieo/qb-weapons] F8 DecreaseAttach Error (Issue #5)


[pjkapj]<https://user-images.githubusercontent.com/83096833/205183411-d06ea754-d032-4d59-8488-557d4f3d4cad.png>

Hey don, after a fresh install. (just changing weapon damage modifier in config) we get this error when shooting. Assume its attachments. this was used with combat pistol no attachments. / standard pistol ammo

**Comment by KSJHub** [comment]
Nothing removed in terms of needing to be there. its all default weapons at moment. added in some repair locations. just looking further down config

**Comment by DonHulieo** [comment]
Dropped a fix for this, hopefully the issue is resolved 🤞

**Comment by KSJHub** [comment]
ok brother. ill get it put in now

**Comment by KSJHub** [comment]
![Screenshot 2022-12-02 035802](https://user-images.githubusercontent.com/83096833/205211800-9e498409-e7e0-4562-89bc-bc7a2964b7cf.png)
 just dropped it in. put in config. change false to true on Config.AttachmentDurabilty same error :S

**Comment by KSJDiamondGaming** [comment]
C:\ScottishNetworkTest\resources\[qb]\qb-weapons\config.lua

**Comment by DonHulieo** [comment]
So I actually can't replicate the error my side, I'm using an unedited qb-inventory as well; so no decay or anything

**Comment by DonHulieo** [comment]
Another update pushed

**Comment by KSJHub** [comment]
understood. using lj inventory with decay this side. so guess that is the issue. it seemed ok with attachment set to false... so can leave that as a solution i guess/

**Comment by DonHulieo** [comment]
It's not because this is designed for inventories with decay lol

**Comment by DonHulieo** [comment]
I just am on a base qbcore framework for my development server, whilst this was developed on a live server I'm no longer working on... This update may just be the go though!

**Comment by KSJHub** [comment]
hmm ok will test the latest. thanks man

**Comment by KSJHub** [comment]
![2444](https://user-images.githubusercontent.com/83096833/205216723-080a59e9-72a4-4fcc-9a89-261a2c59067c.png)
 Its jumped to line 244 :D

**Comment by DonHulieo** [comment]
I'm not getting the error so all I can suggest is, clear server cache and give the server a restart... Possibly join my discord and we can do some more hunting later on! 

For now, I'll leave this issue open for anyone else that might receive the error.

**Comment by KSJHub** [comment]
perfect, im happy to test more with more time.. and thankyou

**Comment by SarangGit** [comment]
This error comes when we use a weapon/attachment which is not mentioned in the Config.DurabilityMultiplier

**Comment by DonHulieo** [comment]
Well that makes complete sense! I guess I can mark this as resolved once some of the missing attachments are added or pr’d.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
